/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package theatre2.dashboard.AdminDashboardFrames;

import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AURORA
 */
public class Screen extends javax.swing.JInternalFrame {

    private String filepath = "src/theatre2/data/screens.txt";

    public Screen() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);

        loadScreensToTable();

    }

    private void loadScreensToTable() {
        DefaultTableModel model = (DefaultTableModel) screenTable.getModel();
        model.setRowCount(0); // clear table

        try {
            FileReader fr = new FileReader("src\\theatre2\\data\\screens.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;
            int no = 1;
            while ((line = br.readLine()) != null) {
                String[] p = line.split("\\|");
                if (p.length >= 5) {
                    // Order in file: name|capacity|status|cols|seatType
                    model.addRow(new Object[]{
                        no++,
                        p[0], // Screen Name
                        p[1], // Capacity
                        p[2], // Status
                        p[3], // Columns Per Row
                        p[4] // SeatTypes
                    });
                }
            }
            br.close();
            fr.close();
        } catch (java.io.FileNotFoundException e) {
            // First run: file may not exist. It's fine.
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading screens: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        screenTable = new javax.swing.JTable();
        deleteScreenButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        screennameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        posterLink = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        capacityField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        columnsPerRowField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        StatusComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        seatTypesComboBox = new javax.swing.JComboBox<>();
        discardButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        screenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Screen Name", "Capacity", "Status", "Columns Per Row", "SeatTypes"
            }
        ));
        jScrollPane2.setViewportView(screenTable);

        deleteScreenButton.setBackground(new java.awt.Color(204, 0, 51));
        deleteScreenButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteScreenButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteScreenButton.setText("Delete Movie");
        deleteScreenButton.setMaximumSize(new java.awt.Dimension(190, 45));
        deleteScreenButton.setMinimumSize(new java.awt.Dimension(190, 45));
        deleteScreenButton.setPreferredSize(new java.awt.Dimension(190, 45));
        deleteScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteScreenButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Screen Database");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(deleteScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 900));

        screennameField.setMinimumSize(new java.awt.Dimension(600, 30));
        screennameField.setPreferredSize(new java.awt.Dimension(600, 30));
        screennameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                screennameFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Screen Name");

        posterLink.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Capacity");

        capacityField.setMinimumSize(new java.awt.Dimension(600, 30));
        capacityField.setPreferredSize(new java.awt.Dimension(600, 30));
        capacityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacityFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Columns Per Row");

        columnsPerRowField.setMinimumSize(new java.awt.Dimension(600, 30));
        columnsPerRowField.setPreferredSize(new java.awt.Dimension(600, 30));
        columnsPerRowField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnsPerRowFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Status");

        StatusComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Running", "Maintanance" }));
        StatusComboBox.setMinimumSize(new java.awt.Dimension(72, 30));
        StatusComboBox.setPreferredSize(new java.awt.Dimension(600, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Seat Types");

        seatTypesComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seatTypesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Premium", "VIP" }));
        seatTypesComboBox.setMinimumSize(new java.awt.Dimension(72, 30));
        seatTypesComboBox.setPreferredSize(new java.awt.Dimension(600, 30));
        seatTypesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTypesComboBoxActionPerformed(evt);
            }
        });

        discardButton.setBackground(new java.awt.Color(204, 0, 51));
        discardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        discardButton.setForeground(new java.awt.Color(255, 255, 255));
        discardButton.setText("Discard");
        discardButton.setMaximumSize(new java.awt.Dimension(190, 45));
        discardButton.setMinimumSize(new java.awt.Dimension(190, 45));
        discardButton.setPreferredSize(new java.awt.Dimension(190, 45));
        discardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 153, 153));
        saveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Save");
        saveButton.setMaximumSize(new java.awt.Dimension(190, 45));
        saveButton.setMinimumSize(new java.awt.Dimension(190, 45));
        saveButton.setPreferredSize(new java.awt.Dimension(190, 45));
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveButtonMousePressed(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(screennameField, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(StatusComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)
                                .addComponent(jLabel10)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(discardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(columnsPerRowField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(seatTypesComboBox, 0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(capacityField, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(posterLink, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(screennameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posterLink, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacityField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(columnsPerRowField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatTypesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void screennameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_screennameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_screennameFieldActionPerformed

    private void capacityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacityFieldActionPerformed

    private void columnsPerRowFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnsPerRowFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnsPerRowFieldActionPerformed

    private void discardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardButtonActionPerformed
        // TODO add your handling code here:
        screennameField.setText("");
        capacityField.setText("");
        StatusComboBox.setSelectedIndex(0);
        columnsPerRowField.setText("");
        seatTypesComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_discardButtonActionPerformed

    private void saveButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonMousePressed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String name = screennameField.getText().trim();
        String capStr = capacityField.getText().trim();
        String status = (String) StatusComboBox.getSelectedItem();
        String colsStr = columnsPerRowField.getText().trim();
        String seat = (String) seatTypesComboBox.getSelectedItem();

        if (name.isEmpty() || capStr.isEmpty() || colsStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill Screen Name, Capacity, and Columns Per Row.");
            return;
        }

        // Very basic number checks
        try {
            Integer.parseInt(capStr);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Capacity must be a number.");
            return;
        }
        try {
            Integer.parseInt(colsStr);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Columns Per Row must be a number.");
            return;
        }

        String line = name + "|" + capStr + "|" + status + "|" + colsStr + "|" + seat;

        try {
            FileWriter fw = new FileWriter(filepath, true);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(line);
            bw.newLine();
            bw.close();
            fw.close();

            JOptionPane.showMessageDialog(this, "Screen saved.");
            loadScreensToTable();     // refresh table
            discardButtonActionPerformed(null); // clear form
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving: " + e.getMessage());
        }
        loadScreensToTable();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void seatTypesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTypesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatTypesComboBoxActionPerformed

    private void deleteScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteScreenButtonActionPerformed
        // TODO add your handling code here:
        int row = screenTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) screenTable.getModel();

        // Values from table (must match how we saved to file)
        String name = (String) model.getValueAt(row, 1);
        String capStr = String.valueOf(model.getValueAt(row, 2));
        String status = (String) model.getValueAt(row, 3);
        String colsStr = String.valueOf(model.getValueAt(row, 4));
        String seat = (String) model.getValueAt(row, 5);

        String targetLine = name + "|" + capStr + "|" + status + "|" + colsStr + "|" + seat;

        // Read file, filter out the targetLine, write back
        try {
            List<String> lines = Files.readAllLines(Paths.get(filepath));
            List<String> newLines = new ArrayList<>();
            for (String line : lines) {
                if (!line.equals(targetLine)) { // basic match on full line
                    newLines.add(line);
                }
            }
            Files.write(Paths.get(filepath), newLines);

            // Remove from table and fix numbering
            model.removeRow(row);
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(i + 1, i, 0); // reset "No" column
            }

            JOptionPane.showMessageDialog(this, "Screen deleted.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting: " + e.getMessage());
        }
    }//GEN-LAST:event_deleteScreenButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> StatusComboBox;
    private javax.swing.JTextField capacityField;
    private javax.swing.JTextField columnsPerRowField;
    private javax.swing.JButton deleteScreenButton;
    private javax.swing.JButton discardButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel posterLink;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable screenTable;
    private javax.swing.JTextField screennameField;
    private javax.swing.JComboBox<String> seatTypesComboBox;
    // End of variables declaration//GEN-END:variables
}
