/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package theatre2.dashboard.UserDashboardFrames;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class PurchaseHistory extends javax.swing.JInternalFrame {

    private String loggedInUsername;
    private String bookingFilePath = "src/theatre2/data/bookings.txt";
    private String userFilePath = "src/theatre2/data/users.txt";

    public PurchaseHistory(String username) {
        this.loggedInUsername = username;
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        // Load data for this user (or empty if username missing)
        loadPurchaseHistory();
    }

    public PurchaseHistory() {
        this(null);
    }

    // --- core: load table for current loggedInUsername ---
    private void loadPurchaseHistory() {
        javax.swing.table.DefaultTableModel model
                = (javax.swing.table.DefaultTableModel) purchaseHistoryTable.getModel();
        model.setRowCount(0);

        // If no logged-in user, show nothing
        if (loggedInUsername == null || loggedInUsername.trim().isEmpty()) {
            return;
        }

        int no = 1;
        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(bookingFilePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                // bookings.txt:
                // 0 Name | 1 Phone | 2 Movie | 3 Date | 4 Screen | 5 Start-End | 6 Qty | 7 Total | 8 ADMIN/Username
                String[] p = line.split("\\|");
                if (p.length < 9) {
                    continue;
                }

                String usernameInFile = p[8].trim();
                if (!usernameInFile.equalsIgnoreCase(loggedInUsername)) {
                    continue;
                }

                String movie = p[2].trim();
                String date = p[3].trim();
                String screen = p[4].trim();
                String time = p[5].trim();
                String qty = p[6].trim();
                String total = p[7].trim();

                model.addRow(new Object[]{no++, movie, screen, date, time, qty, total});
            }
        } catch (java.io.FileNotFoundException e) {
            // ok if file doesn't exist yet
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading purchases: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        purchaseHistoryTable = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Purchase History");

        purchaseHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Movie Name", "Screen Name", "Date", "Time", "Total Ticket", "Total Price"
            }
        ));
        jScrollPane1.setViewportView(purchaseHistoryTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable purchaseHistoryTable;
    // End of variables declaration//GEN-END:variables
}
