/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package theatre2.dashboard;

import theatre2.LoginSignup.LoginFrame;
import theatre2.dashboard.AdminDashboardFrames.Home;
import theatre2.dashboard.AdminDashboardFrames.Movie;
import theatre2.dashboard.AdminDashboardFrames.Show;
import theatre2.dashboard.AdminDashboardFrames.Screen;
import theatre2.dashboard.AdminDashboardFrames.Ticket;
import theatre2.dashboard.AdminDashboardFrames.Booking;

import java.awt.Color;

/**
 *
 * @author AURORA
 */
public class AdminDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    Color DefaultColor, ClickedColor;

    public AdminDashboard() {
        initComponents();
        DefaultColor = new Color(0, 153, 153);
        ClickedColor = new Color(0, 204, 204);

        Home home = new Home();
        MainDesktopPane.removeAll();
        MainDesktopPane.add(home);
        home.setBounds(0, 0, MainDesktopPane.getWidth(), MainDesktopPane.getHeight());
        home.setVisible(true);
        MainDesktopPane.revalidate();
        MainDesktopPane.repaint();

        HomeButton.setBackground(ClickedColor);
        MovieButton.setBackground(DefaultColor);
        ShowButton.setBackground(DefaultColor);
        ScreenButton.setBackground(DefaultColor);
        TicketButton.setBackground(DefaultColor);
        BookingButton.setBackground(DefaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainDesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MovieButton = new javax.swing.JButton();
        TicketButton = new javax.swing.JButton();
        BookingButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        ShowButton = new javax.swing.JButton();
        ScreenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainDesktopPane.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout MainDesktopPaneLayout = new javax.swing.GroupLayout(MainDesktopPane);
        MainDesktopPane.setLayout(MainDesktopPaneLayout);
        MainDesktopPaneLayout.setHorizontalGroup(
            MainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        MainDesktopPaneLayout.setVerticalGroup(
            MainDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(250, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(250, 900));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatre2/icon/logo1.png"))); // NOI18N

        MovieButton.setBackground(new java.awt.Color(0, 153, 153));
        MovieButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MovieButton.setForeground(new java.awt.Color(255, 255, 255));
        MovieButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatre2/icon/clapperboard.png"))); // NOI18N
        MovieButton.setText("  Movie Management");
        MovieButton.setBorder(null);
        MovieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieButtonActionPerformed(evt);
            }
        });

        TicketButton.setBackground(new java.awt.Color(0, 153, 153));
        TicketButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TicketButton.setForeground(new java.awt.Color(255, 255, 255));
        TicketButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatre2/icon/ticket.png"))); // NOI18N
        TicketButton.setText("  Ticket Pricing");
        TicketButton.setBorder(null);
        TicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketButtonActionPerformed(evt);
            }
        });

        BookingButton.setBackground(new java.awt.Color(0, 153, 153));
        BookingButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BookingButton.setForeground(new java.awt.Color(255, 255, 255));
        BookingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatre2/icon/booking.png"))); // NOI18N
        BookingButton.setText("  Booking Management");
        BookingButton.setBorder(null);
        BookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingButtonActionPerformed(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(204, 0, 0));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatre2/icon/male_user_50px.png"))); // NOI18N
        LogoutButton.setText("  Logout");
        LogoutButton.setBorder(null);
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(0, 153, 153));
        HomeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatre2/icon/home.png"))); // NOI18N
        HomeButton.setText("  Home");
        HomeButton.setBorder(null);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        ShowButton.setBackground(new java.awt.Color(0, 153, 153));
        ShowButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ShowButton.setForeground(new java.awt.Color(255, 255, 255));
        ShowButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatre2/icon/calendar.png"))); // NOI18N
        ShowButton.setText("  Show Management");
        ShowButton.setBorder(null);
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });

        ScreenButton.setBackground(new java.awt.Color(0, 153, 153));
        ScreenButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ScreenButton.setForeground(new java.awt.Color(255, 255, 255));
        ScreenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatre2/icon/theater.png"))); // NOI18N
        ScreenButton.setText("  Screen Management");
        ScreenButton.setBorder(null);
        ScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(MovieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TicketButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ShowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ScreenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MovieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TicketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainDesktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        dispose(); // close the login frame
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void MovieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieButtonActionPerformed
        // TODO add your handling code here:
        Movie movie = new Movie();
        MainDesktopPane.removeAll();
        MainDesktopPane.add(movie);
        movie.setBounds(0, 0, MainDesktopPane.getWidth(), MainDesktopPane.getHeight());
        movie.setVisible(true);
        MainDesktopPane.revalidate();
        MainDesktopPane.repaint();

        HomeButton.setBackground(DefaultColor);
        MovieButton.setBackground(ClickedColor);
        ShowButton.setBackground(DefaultColor);
        ScreenButton.setBackground(DefaultColor);
        TicketButton.setBackground(DefaultColor);
        BookingButton.setBackground(DefaultColor);

        //@author Naziba Ali

    }//GEN-LAST:event_MovieButtonActionPerformed

    private void TicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketButtonActionPerformed
        // TODO add your handling code here:
        Ticket ticket = new Ticket();
        MainDesktopPane.removeAll();
        MainDesktopPane.add(ticket);
        ticket.setBounds(0, 0, MainDesktopPane.getWidth(), MainDesktopPane.getHeight());
        ticket.setVisible(true);
        MainDesktopPane.revalidate();
        MainDesktopPane.repaint();

        HomeButton.setBackground(DefaultColor);
        MovieButton.setBackground(DefaultColor);
        ShowButton.setBackground(DefaultColor);
        ScreenButton.setBackground(DefaultColor);
        TicketButton.setBackground(ClickedColor);
        BookingButton.setBackground(DefaultColor);
    }//GEN-LAST:event_TicketButtonActionPerformed

    private void BookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingButtonActionPerformed
        // TODO add your handling code here:
        Booking booking = new Booking();
        MainDesktopPane.removeAll();
        MainDesktopPane.add(booking);
        booking.setBounds(0, 0, MainDesktopPane.getWidth(), MainDesktopPane.getHeight());
        booking.setVisible(true);
        MainDesktopPane.revalidate();
        MainDesktopPane.repaint();

        HomeButton.setBackground(DefaultColor);
        MovieButton.setBackground(DefaultColor);
        ShowButton.setBackground(DefaultColor);
        ScreenButton.setBackground(DefaultColor);
        TicketButton.setBackground(DefaultColor);
        BookingButton.setBackground(ClickedColor);
    }//GEN-LAST:event_BookingButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        MainDesktopPane.removeAll();
        MainDesktopPane.add(home);
        home.setBounds(0, 0, MainDesktopPane.getWidth(), MainDesktopPane.getHeight());
        home.setVisible(true);
        MainDesktopPane.revalidate();
        MainDesktopPane.repaint();

        HomeButton.setBackground(ClickedColor);
        MovieButton.setBackground(DefaultColor);
        ShowButton.setBackground(DefaultColor);
        ScreenButton.setBackground(DefaultColor);
        TicketButton.setBackground(DefaultColor);
        BookingButton.setBackground(DefaultColor);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        // TODO add your handling code here:
        Show show = new Show();
        MainDesktopPane.removeAll();
        MainDesktopPane.add(show);
        show.setBounds(0, 0, MainDesktopPane.getWidth(), MainDesktopPane.getHeight());
        show.setVisible(true);
        MainDesktopPane.revalidate();
        MainDesktopPane.repaint();

        HomeButton.setBackground(DefaultColor);
        MovieButton.setBackground(DefaultColor);
        ShowButton.setBackground(ClickedColor);
        ScreenButton.setBackground(DefaultColor);
        TicketButton.setBackground(DefaultColor);
        BookingButton.setBackground(DefaultColor);
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void ScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenButtonActionPerformed
        // TODO add your handling code here:
        Screen screen = new Screen();
        MainDesktopPane.removeAll();
        MainDesktopPane.add(screen);
        screen.setBounds(0, 0, MainDesktopPane.getWidth(), MainDesktopPane.getHeight());
        screen.setVisible(true);
        MainDesktopPane.revalidate();
        MainDesktopPane.repaint();

        HomeButton.setBackground(DefaultColor);
        MovieButton.setBackground(DefaultColor);
        ShowButton.setBackground(DefaultColor);
        ScreenButton.setBackground(ClickedColor);
        TicketButton.setBackground(DefaultColor);
        BookingButton.setBackground(DefaultColor);
    }//GEN-LAST:event_ScreenButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JDesktopPane MainDesktopPane;
    private javax.swing.JButton MovieButton;
    private javax.swing.JButton ScreenButton;
    private javax.swing.JButton ShowButton;
    private javax.swing.JButton TicketButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
